/*
 * Copyright 2016 AUTHORS. Patrick S Sewell, Paul M Dyer, Taehyeok Lee, 
 * Benjamin C Ferguson, Hyunki J KIm Permission is granted to copy, distribute 
 * and/or modify this document under the terms of the GNU Free Documentation 
 * License, Version 1.3, (3 November 2008) or any later version published by 
 * the Free Software Foundation; with no Invariant Sections, with no 
 * Front-Cover Texts, and with no Back-Cover Texts. A copy of the license 
 * can be found at http://www.gnu.org/copyleft/fdl.html
 */
package Views;

import Common.UserSettings;
import Controllers.AdminViewController;
import javax.swing.JOptionPane;

/**
 * The Admin view.
 * @author Patrick Sewell
 */
public class AdminView extends javax.swing.JFrame {

    // <editor-fold defaultstate="collapsed" desc="Member Variables"> 
    private final AdminViewController controller;

    // </editor-fold>
    /**
     * Creates new form AdminView.
     * 
     * @param controller The AdminViewController for the view
     */
    public AdminView(AdminViewController controller) {
        this.controller = controller;
        load();
    }

    // </editor-fold> 
    private void load() {
        initComponents();
        setThemeColors();
        setTitle("Administrator Navigation");

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Resources/icon.png")).getImage());

        setResizable(false);
        setVisible(true);
    }

    private void setThemeColors() {
        jPanel1.setBackground(UserSettings.selectedTheme.getBackgroundColor());

        accountManagerButton.setBackground(UserSettings.selectedTheme.getButtonBackgroundColor());
        accountPersonLinkManagerButton.setBackground(UserSettings.selectedTheme.getButtonBackgroundColor());
        personManagerButton.setBackground(UserSettings.selectedTheme.getButtonBackgroundColor());
        userManagerButton.setBackground(UserSettings.selectedTheme.getButtonBackgroundColor());
        exitButton.setBackground(UserSettings.selectedTheme.getButtonBackgroundColor());

        accountManagerButton.setForeground(UserSettings.selectedTheme.getTextColor());
        accountPersonLinkManagerButton.setForeground(UserSettings.selectedTheme.getTextColor());
        personManagerButton.setForeground(UserSettings.selectedTheme.getTextColor());
        userManagerButton.setForeground(UserSettings.selectedTheme.getTextColor());
        exitButton.setForeground(UserSettings.selectedTheme.getTextColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        personManagerButton = new javax.swing.JButton();
        userManagerButton = new javax.swing.JButton();
        accountManagerButton = new javax.swing.JButton();
        accountPersonLinkManagerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personManagerButton.setText("Person Manager");
        personManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personManagerButtonActionPerformed(evt);
            }
        });

        userManagerButton.setText("User Manager");
        userManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagerButtonActionPerformed(evt);
            }
        });

        accountManagerButton.setText("Account Manager");
        accountManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountManagerButtonActionPerformed(evt);
            }
        });

        accountPersonLinkManagerButton.setText("Account Person Link Manager");
        accountPersonLinkManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountPersonLinkManagerButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logo.png"))); // NOI18N

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(personManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountPersonLinkManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accountManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accountPersonLinkManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personManagerButtonActionPerformed
        controller.executeNavigatePersonList();
    }//GEN-LAST:event_personManagerButtonActionPerformed

    private void userManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagerButtonActionPerformed
        controller.executeNavigateUserList();
    }//GEN-LAST:event_userManagerButtonActionPerformed

    private void accountManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountManagerButtonActionPerformed
        controller.executeNavigateAccountList();
    }//GEN-LAST:event_accountManagerButtonActionPerformed

    private void accountPersonLinkManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountPersonLinkManagerButtonActionPerformed
        controller.executeNavigateAccountPersonMapList();
    }//GEN-LAST:event_accountPersonLinkManagerButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int n = JOptionPane.showConfirmDialog(jPanel1,
                    "Exit ATM?", "Confirm Exit",
                    JOptionPane.OK_CANCEL_OPTION);
            if (n == JOptionPane.YES_OPTION) {
                controller.executeQuit();
            }
    }//GEN-LAST:event_exitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountManagerButton;
    private javax.swing.JButton accountPersonLinkManagerButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton personManagerButton;
    private javax.swing.JButton userManagerButton;
    // End of variables declaration//GEN-END:variables
}
