/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Common.AesEncryption;
import Controllers.LogOnViewController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class LogOnView extends javax.swing.JFrame {

    // <editor-fold defaultstate="collapsed" desc="Member Variables"> 
    private final LogOnViewController controller;

    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Constructors"> 
    public LogOnView(LogOnViewController controller) {
        this.controller = controller;
        load();
    }

    // </editor-fold> 
    private void load() {
        initComponents();
        logOnFailureLabel.setVisible(false);

        userNameField.setText("admin");
        passwordField.setText("password");

        setVisible(true);
    }

    private void doKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            doLogOn();
        }
    }

    private void doLogOn() {  
        try {
            String password = AesEncryption.encryptText(new String(passwordField.getPassword()));
            boolean successful = controller.executeLogOn(userNameField.getText(), password);

            if (successful) {
                logOnFailureLabel.setVisible(false);
                logOnPanel.setVisible(false);

            } else {
                logOnFailureLabel.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(logOnPanel, "Password encryption failure. ");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Methods"> 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logOnPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logOnFailureLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        logOnButton = new javax.swing.JButton();
        provisionDatabaseButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logOnPanel.setDoubleBuffered(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("User Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password:");

        logOnFailureLabel.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        logOnFailureLabel.setForeground(new java.awt.Color(255, 0, 0));
        logOnFailureLabel.setText("The entered credentials could not be validated.");

        userNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userNameField.setNextFocusableComponent(passwordField);
        userNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameFieldKeyPressed(evt);
            }
        });

        logOnButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logOnButton.setText("Log On");
        logOnButton.setNextFocusableComponent(userNameField);
        logOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOnButtonActionPerformed(evt);
            }
        });
        logOnButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logOnButtonKeyPressed(evt);
            }
        });

        provisionDatabaseButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        provisionDatabaseButton.setText("Provision Database");
        provisionDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provisionDatabaseButtonActionPerformed(evt);
            }
        });

        passwordField.setNextFocusableComponent(logOnButton);
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout logOnPanelLayout = new javax.swing.GroupLayout(logOnPanel);
        logOnPanel.setLayout(logOnPanelLayout);
        logOnPanelLayout.setHorizontalGroup(
            logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOnPanelLayout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(provisionDatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logOnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logOnPanelLayout.createSequentialGroup()
                        .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameField)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(logOnButton))
                    .addComponent(logOnFailureLabel))
                .addGap(54, 54, 54))
        );
        logOnPanelLayout.setVerticalGroup(
            logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logOnPanelLayout.createSequentialGroup()
                        .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(logOnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logOnPanelLayout.createSequentialGroup()
                        .addComponent(logOnButton)
                        .addGap(42, 42, 42)))
                .addComponent(logOnFailureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(provisionDatabaseButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logOnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logOnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void provisionDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provisionDatabaseButtonActionPerformed
        controller.executeProvisionDatabase();
    }//GEN-LAST:event_provisionDatabaseButtonActionPerformed

    private void logOnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOnButtonActionPerformed
        doLogOn();
    }//GEN-LAST:event_logOnButtonActionPerformed

    private void userNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameFieldKeyPressed
        doKeyPressed(evt);
    }//GEN-LAST:event_userNameFieldKeyPressed

    private void logOnButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logOnButtonKeyPressed
        doKeyPressed(evt);
    }//GEN-LAST:event_logOnButtonKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        doKeyPressed(evt);
    }//GEN-LAST:event_passwordFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logOnButton;
    private javax.swing.JLabel logOnFailureLabel;
    private javax.swing.JPanel logOnPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton provisionDatabaseButton;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
